<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-DalinaV/blob/main/Modulo5_DalinaAideeVillaOcelotl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [2]:
import numpy as np

np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [3]:
np.dot(np.array([1,-1]),np.array([1,1])) #producto punto

0

In [5]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])

#np.dot(A,B) No tienen las mismas dimensiones

**Aplication Program interface API**

In [8]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [9]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [10]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])